CREATE TABLE users (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	first_name MEDIUMTEXT NOT NULL,
	last_name MEDIUMTEXT NOT NULL,
	password MEDIUMTEXT NOT NULL,
	gender TINYTEXT NOT NULL,
	phone MEDIUMTEXT NOT NULL
);